### ISSUE TITLE
Italian version

### ISSUE THREAD

**Issue by Christianlm** [ABuffEr/NVDASnapshotDownloader#2]
This is a possible  version translated in italian language...
[NVDASnapshotDownloader-2.0-it.zip](https://github.com/ABuffEr/NVDASnapshotDownloader/files/3555455/NVDASnapshotDownloader-2.0-it.zip)

**Comment by ABuffEr** [comment]
Hi @Christianlm ,
thanks! Added release and updated readme :)

**Comment by Christianlm** [comment]
Thanks, closing via commit 7bb274e546c5bbe4dd0a00465bf30573c8093b65
